# Generated by Django 5.2.6 on 2025-09-06 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('learning_weights', models.JSONField(default=dict)),
                ('total_interactions', models.IntegerField(default=0)),
                ('avg_satisfaction', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=50)),
                ('pattern_data', models.JSONField()),
                ('effectiveness_score', models.FloatField()),
                ('usage_count', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('data_content', models.TextField()),
                ('storage_recommendation', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('features_analyzed', models.JSONField()),
                ('processing_time', models.FloatField()),
                ('user_feedback', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
            ],
        ),
    ]
