# Generated by Django 5.2.6 on 2025-09-06 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpattern',
            name='effectiveness_score',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='pattern_data',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='pattern_type',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='context_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='feedback_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='storage_choice',
            field=models.CharField(default='hybrid_intelligent', max_length=100),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='weights_after',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='learningpattern',
            name='weights_before',
            field=models.JSONField(default=dict),
        ),
    ]
